version: "3"
services:
  react-app:
    image: varenyam/jiva:react-app
    restart: unless-stopped
    ports:
      - "80:3000"

    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-app
  api-server:
    image: varenyam/jiva:api-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
